[package]
name = "remux-tui"
version = "0.7.0"
edition = "2021"
license = "MIT"

[dependencies]
remux-core = { path = "../core" }
remux-config = { path = "../config" }
mlua = { version = "0.9", features = ["lua54"] }
crossterm = "0.27"
ratatui = "0.26"
unicode-width = "0.1"